# Generated by Django 3.1.6 on 2021-02-18 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='checklist.comment')),
            ],
        ),
    ]
