# Generated by Django 3.1.6 on 2021-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
