# Generated by Django 3.1.6 on 2021-02-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20210218_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='checklist.checklist'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='related_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='checklist.category'),
        ),
    ]
