# Generated by Django 3.1.6 on 2021-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_auto_20210219_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='subtask',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='checklist.Comment'),
        ),
    ]
