# Generated by Django 3.1.6 on 2021-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_auto_20210223_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='subtask', to='checklist.Comment'),
        ),
    ]
