# Generated by Django 3.1.6 on 2021-02-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_auto_20210223_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='related_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='checklist.category'),
        ),
    ]
